import { loadCatalog, getItemsList, getMovesList, getSpeciesMap, getSpeciesFormMetaMap } from './src/puse/catalog.js';
import {
  getParty, updatePartyIvs, updatePartyEvs, updatePartyMoves, updatePartyNature,
  updatePartyItem, updatePartyAbilitySwitch, updatePartyIdentity, updatePartySpecies,
  updatePartyLevel, updatePartyNickname
} from './src/puse/party.js';
import { loadPcContext, getPcBox, editPcMonFull, insertPcMon, getWritablePcSlots } from './src/puse/pc.js';
import { findActiveSectionById } from './src/puse/sections.js';
import { saveAll } from './src/puse/commit.js';
import { convertSaveBytes } from './src/puse/saveConvert.js';
import { ru16, ru32, wu16, wu32, wu8 } from './src/puse/binary.js';
import { getSpeciesGrowthRate, getExpAtLevel } from './src/puse/growth.js';
import speciesIdentityMeta from './src/puse/speciesIdentityMeta.json.js';
import speciesAbilitiesMeta from './src/puse/speciesAbilitiesMeta.json.js';
import abilitiesCatalog from './src/puse/abilitiesCatalog.json.js';

const NATURES = ['Hardy','Lonely','Brave','Adamant','Naughty','Bold','Docile','Relaxed','Impish','Lax','Timid','Hasty','Serious','Jolly','Naive','Modest','Mild','Quiet','Bashful','Rash','Calm','Gentle','Sassy','Careful','Quirky'];
const STATS = [['HP','HP'],['Atk','Attack'],['Def','Defense'],['Spe','Speed'],['SpA','Sp. Atk'],['SpD','Sp. Def']];
const TRAINER_SECTION_ID = 1;
const PARTY_COUNT_OFFSET = 0x34;
const PARTY_START_OFFSET = 0x38;
const PARTY_MON_SIZE = 100;
const PARTY_STATUS_OFFSET = 0x50;
const PARTY_MAIL_OFFSET = 0x55;
const PARTY_CURR_HP_OFFSET = 0x56;
const PARTY_MAX_HP_OFFSET = 0x58;
const $ = (id) => document.getElementById(id);
const state = { bytes:null, original:null, fileName:'', pc:null, species:null, speciesMeta:null, speciesList:[], items:[], moves:[], tab:'party', box:1, selected:null, editCount:0, formDirty:false };

function message(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error)}
function option(value,label){return new Option(label,String(value))}
function setOptions(select,entries,value,emptyLabel=null){const f=document.createDocumentFragment();if(emptyLabel!==null)f.append(option(0,emptyLabel));for(const e of entries)f.append(option(e.id,e.name));const target=String(value??0);if(![...f.children].some(n=>n.value===target))f.append(option(target,`Unknown #${target}`));select.replaceChildren(f);select.value=target}
function catalogFor(id){if(id==='species'||id==='create-species')return state.speciesList;if(id==='item')return state.items;return state.moves}
function filterSelect(id){const search=$(`search-${id}`),select=$(id),query=search.value.trim().toLocaleLowerCase();const current=select.value;const source=catalogFor(id);const matches=query?source.filter(row=>row.name.toLocaleLowerCase().includes(query)||String(row.id)===query):source;const matchCount=matches.length;const selected=source.find(row=>String(row.id)===current);if(selected&&!matches.some(row=>String(row.id)===current))matches.push(selected);setOptions(select,matches,current,id.startsWith('move-')?'— Empty move —':id==='item'?'None':null);search.setAttribute('aria-label',`Search ${id.replace(/-\d/, '')}: ${matchCount} matches`)}
function resetSearch(id){const search=$(`search-${id}`);if(search)search.value=''}
function speciesName(id){return state.species?.get?.(Number(id))||`Species #${id}`}
function buildSpeciesList(){state.speciesList=[...state.species.entries()].filter(([id])=>Number(id)>0).map(([id,name])=>({id:Number(id),name:`${name} · #${id}`})).sort((a,b)=>a.id-b.id)}
function setSpeciesOptions(select,value){setOptions(select,state.speciesList,value)}
function abilityChoices(speciesId){if(Number(speciesId)===1302)return [{id:0,name:'Eclipse Heart · Virtual'}];const meta=speciesAbilitiesMeta[String(speciesId)];if(!meta)return [];return [['ability_1_id','Standard',0],['ability_2_id','Second',1],['hidden_ability_id','Hidden',2]].flatMap(([key,label,id])=>{const ability=Number(meta[key]);if(!Number.isInteger(ability)||ability<=0)return [];return [{id,name:`${abilitiesCatalog[String(ability)]||`Ability #${ability}`} · ${label}`}];})}
function populateAbility(speciesId,wanted){const choices=abilityChoices(speciesId);const select=$('ability');select.replaceChildren(...(choices.length?choices.map(row=>option(row.id,row.name)):[option(0,'Ability data unavailable')]));select.disabled=!choices.length||Number(speciesId)===1302;select.value=String(choices.some(row=>row.id===Number(wanted))?wanted:choices[0]?.id??0)}

function getMon(){if(!state.selected)return null;if(state.selected.kind==='party')return getParty(state.bytes,state.species,state.speciesMeta).find(m=>m.index===state.selected.index)||null;return getPcBox(state.pc,state.selected.box,state.species,state.speciesMeta).find(m=>m.slot===state.selected.slot)||null}
function currentList(){return state.tab==='party'?getParty(state.bytes,state.species,state.speciesMeta):getPcBox(state.pc,state.box,state.species,state.speciesMeta)}

function card(mon){const b=document.createElement('button');b.type='button';b.className='mon-card';const selected=state.selected&&((state.tab==='party'&&state.selected.kind==='party'&&state.selected.index===mon.index)||(state.tab==='pc'&&state.selected.kind==='pc'&&state.selected.box===mon.box&&state.selected.slot===mon.slot));if(selected)b.classList.add('selected');const a=document.createElement('span');a.className='mon-avatar';a.textContent=(mon.species_display_name||mon.nickname||'?').slice(0,1).toUpperCase();const c=document.createElement('span');c.className='mon-copy';const n=document.createElement('strong');n.textContent=mon.species_label||mon.species_name||`Species #${mon.species_id}`;const meta=document.createElement('small');meta.textContent=`${state.tab==='party'?`Slot ${mon.index+1}`:`Slot ${mon.slot}`} · Lv ${mon.level}${mon.is_shiny?' · ✦ Shiny':''}`;c.append(n,meta);b.append(a,c);b.addEventListener('click',()=>selectMon(state.tab==='party'?{kind:'party',index:mon.index}:{kind:'pc',box:mon.box,slot:mon.slot}));return b}
function renderList(){const mons=currentList();$('mon-list').replaceChildren(...mons.map(card));$('empty-list').hidden=mons.length>0;if(state.tab==='pc')$('box-count').textContent=`${mons.length} Pokémon`;$('party-tab').classList.toggle('active',state.tab==='party');$('pc-tab').classList.toggle('active',state.tab==='pc');$('party-tab').setAttribute('aria-selected',String(state.tab==='party'));$('pc-tab').setAttribute('aria-selected',String(state.tab==='pc'));$('box-controls').hidden=state.tab!=='pc';$('add-mon').textContent=state.tab==='party'?'+ Add to Party':'+ Add to PC'}
function statValue(mon,key,group){return Number(mon[group]?.[key]??(key==='Spe'?mon[group]?.Spd:null)??0)}
function renderStats(id,mon,group,max){const fields=STATS.map(([key,label])=>{const w=document.createElement('label');w.textContent=label;const i=document.createElement('input');i.type='number';i.inputMode='numeric';i.min='0';i.max=String(max);i.step='1';i.id=`${group}-${key}`;i.value=String(statValue(mon,key,group));w.append(i);return w});$(id).replaceChildren(...fields)}

function genderMode(speciesId){const t=Number(speciesIdentityMeta?.[String(Number(speciesId))]?.gender_threshold);if(!Number.isInteger(t))return 'unknown';if(t===255)return 'genderless';if(t===0)return 'fixed_male';if(t===254)return 'fixed_female';return 'dynamic'}
function safeGender(speciesId,wanted){const mode=genderMode(speciesId);if(mode==='genderless')return 'genderless';if(mode==='fixed_male')return 'male';if(mode==='fixed_female')return 'female';if(mode==='dynamic'&&(wanted==='male'||wanted==='female'))return wanted;return undefined}
function populateGender(speciesId,wanted){const g=$('gender');const mode=genderMode(speciesId);if(mode==='dynamic'){g.replaceChildren(option('male','Male'),option('female','Female'));g.disabled=false;g.value=(wanted==='female'?'female':'male');return}const value=safeGender(speciesId,wanted)||wanted||'unknown';g.replaceChildren(option(value,value.replace(/^./,c=>c.toUpperCase()).replace('_',' ')));g.disabled=true;g.value=value}

function renderEditor(){const mon=getMon();if(!mon){$('editor').hidden=true;return}$('editor').hidden=false;$('editor-name').textContent=mon.species_label||mon.species_name||`Species #${mon.species_id}`;$('editor-location').textContent=state.selected.kind==='party'?`Party · Slot ${mon.index+1}`:`${mon.box===26?'Preset':`Box ${mon.box}`} · Slot ${mon.slot}`;for(const id of ['species','item','move-0','move-1','move-2','move-3'])resetSearch(id);setSpeciesOptions($('species'),mon.species_id);setOptions($('nature'),NATURES.map((name,id)=>({id,name})),mon.nature_id);populateAbility(mon.species_id,mon.current_ability_index);setOptions($('item'),state.items,mon.item_id,'None');$('shiny').checked=Boolean(mon.is_shiny);populateGender(mon.species_id,mon.gender);for(let i=0;i<4;i++)setOptions($(`move-${i}`),state.moves,mon.moves?.[i]??0,'— Empty move —');renderStats('iv-grid',mon,'ivs',31);renderStats('ev-grid',mon,'evs',252);state.formDirty=false}
function confirmDiscard(){return !state.formDirty||window.confirm('Discard unsaved Pokémon changes?')}
function selectMon(selection){if(!confirmDiscard())return;state.selected=selection;$('creator').hidden=true;renderList();renderEditor();$('editor').scrollIntoView({behavior:'smooth',block:'nearest'})}
function setTab(tab){if(state.tab===tab||!confirmDiscard())return;state.tab=tab;state.selected=null;state.formDirty=false;$('creator').hidden=true;renderList();renderEditor()}

function readInt(id,min,max){const raw=$(id).value;const v=Number(raw);if(raw===''||!Number.isInteger(v)||v<min||v>max)throw new Error(`${$(id).closest('label')?.textContent?.trim()||id} must be ${min}–${max}.`);return v}
function readFields(){const ivs={},evs={};for(const [key]of STATS){ivs[key]=readInt(`ivs-${key}`,0,31);evs[key]=readInt(`evs-${key}`,0,252)}const total=Object.values(evs).reduce((a,b)=>a+b,0);if(total>510)throw new Error(`EV total is ${total}; maximum is 510.`);const species=readInt('species',1,2500);if(!state.species.has(species))throw new Error('Select a Pokémon species from the list.');const ability=Number($('ability').value);const validAbilities=abilityChoices(species);if(validAbilities.length&&!validAbilities.some(row=>row.id===ability))throw new Error('Choose an ability available to this species.');return{species,ability:validAbilities.length?ability:null,ivs,evs,moves:[0,1,2,3].map(i=>readInt(`move-${i}`,0,1023)),nature:readInt('nature',0,24),item:readInt('item',0,65535),shiny:$('shiny').checked,gender:$('gender').value}}
function expAtLevelForSpecies(speciesId,level){const rate=getSpeciesGrowthRate(speciesId);return Math.max(1,getExpAtLevel(rate===null?0:rate,level))}

function applyChanges(event){event.preventDefault();if(!state.selected)return;try{const before=getMon();if(!before)throw new Error('Selected Pokémon is no longer available.');const values=readFields();const next=saveAll(new Uint8Array(state.bytes),state.pc);const nextPc=loadPcContext(next);const speciesChanged=Number(before.species_id)!==Number(values.species);const desiredGender=safeGender(values.species,values.gender);
  if(state.selected.kind==='party'){
    const index=state.selected.index;
    if(speciesChanged){updatePartySpecies(next,index,{species_id:values.species});updatePartyLevel(next,index,{target_level:before.level});}
    updatePartyMoves(next,index,{moves:values.moves});
    updatePartyIvs(next,index,{hp:values.ivs.HP,atk:values.ivs.Atk,dfe:values.ivs.Def,spe:values.ivs.Spe,spa:values.ivs.SpA,spd:values.ivs.SpD});
    updatePartyEvs(next,index,{hp:values.evs.HP,atk:values.evs.Atk,dfe:values.evs.Def,spe:values.evs.Spe,spa:values.evs.SpA,spd:values.evs.SpD});
    updatePartyNature(next,index,{nature_id:values.nature});updatePartyItem(next,index,{item_id:values.item});if(values.ability!==null||speciesChanged)updatePartyAbilitySwitch(next,index,{ability_index:values.ability??0});updatePartyIdentity(next,index,{shiny:values.shiny,gender:desiredGender});
  }else{
    editPcMonFull(nextPc,{box:state.selected.box,slot:state.selected.slot,species_id:values.species,exp:speciesChanged?expAtLevelForSpecies(values.species,before.level):undefined,moves:values.moves,ivs:values.ivs,evs:values.evs,nature_id:values.nature,item_id:values.item,current_ability_index:values.ability??(speciesChanged?0:before.current_ability_index),shiny:values.shiny,gender:desiredGender});
  }
  saveAll(next,nextPc);const committedPc=loadPcContext(next);const rb=state.selected.kind==='party'?getParty(next,state.species,state.speciesMeta).find(m=>m.index===state.selected.index):getPcBox(committedPc,state.selected.box,state.species,state.speciesMeta).find(m=>m.slot===state.selected.slot);if(!rb||Number(rb.species_id)!==Number(values.species)||rb.nature_id!==values.nature||rb.item_id!==values.item||rb.is_shiny!==values.shiny||(values.ability!==null&&rb.current_ability_index!==values.ability)||values.moves.some((v,i)=>rb.moves[i]!==v))throw new Error('The save did not read back with the requested values. No changes were applied.');state.bytes=next;state.pc=committedPc;state.editCount++;state.formDirty=false;$('edit-count').textContent=`${state.editCount} saved ${state.editCount===1?'edit':'edits'}`;renderList();renderEditor();message(speciesChanged?'Species and Pokémon changes saved in this session.':'Pokémon changes saved in this session.');
}catch(error){message(error.message||String(error),true)}}

function partyCount(buffer){const active=findActiveSectionById(buffer,TRAINER_SECTION_ID);if(!active)throw new Error('Trainer save section not found.');return Math.min(6,ru32(buffer,active.off+PARTY_COUNT_OFFSET))}
function appendPartyPokemon(buffer,{speciesId,level}){const active=findActiveSectionById(buffer,TRAINER_SECTION_ID);if(!active)throw new Error('Trainer save section not found.');const count=Math.min(6,ru32(buffer,active.off+PARTY_COUNT_OFFSET));if(count>=6)throw new Error('Party is full. Add the Pokémon to a PC box instead.');if(count<1)throw new Error('This test build needs at least one existing party Pokémon to inherit safe owner/runtime metadata.');const sourceOff=active.off+PARTY_START_OFFSET;const targetOff=active.off+PARTY_START_OFFSET+(count*PARTY_MON_SIZE);const template=buffer.slice(sourceOff,sourceOff+PARTY_MON_SIZE);buffer.set(template,targetOff);wu32(buffer,active.off+PARTY_COUNT_OFFSET,count+1);
  updatePartySpecies(buffer,count,{species_id:speciesId});
  updatePartyNickname(buffer,count,{nickname:speciesName(speciesId)});
  updatePartyLevel(buffer,count,{target_level:level});
  updatePartyMoves(buffer,count,{moves:[0,0,0,0]});
  updatePartyIvs(buffer,count,{hp:31,atk:31,dfe:31,spe:31,spa:31,spd:31});
  updatePartyEvs(buffer,count,{hp:0,atk:0,dfe:0,spe:0,spa:0,spd:0});
  updatePartyNature(buffer,count,{nature_id:0});
  updatePartyItem(buffer,count,{item_id:0});
  updatePartyAbilitySwitch(buffer,count,{ability_index:0});
  updatePartyIdentity(buffer,count,{shiny:false,gender:safeGender(speciesId,undefined)});
  wu32(buffer,targetOff+PARTY_STATUS_OFFSET,0);wu8(buffer,targetOff+PARTY_MAIL_OFFSET,0xFF);wu16(buffer,targetOff+PARTY_CURR_HP_OFFSET,ru16(buffer,targetOff+PARTY_MAX_HP_OFFSET));
  return count;
}

function openCreator(){if(!state.bytes)return;resetSearch('create-species');if(state.tab==='party'&&partyCount(state.bytes)>=6){message('Party is full. Switch to PC Boxes to add another Pokémon.',true);return}state.selected=null;renderEditor();setSpeciesOptions($('create-species'),1);$('create-level').value='5';$('creator-location').textContent=state.tab==='party'?`Party · next free slot ${partyCount(state.bytes)+1}`:`Box ${state.box} · first writable empty slot`;$('creator').hidden=false;$('creator').scrollIntoView({behavior:'smooth',block:'nearest'})}
function closeCreator(){$('creator').hidden=true}
function createPokemon(event){event.preventDefault();try{const speciesId=readInt('create-species',1,2500);if(!state.species.has(speciesId))throw new Error('Select a Pokémon species from the list.');const level=readInt('create-level',1,100);const next=saveAll(new Uint8Array(state.bytes),state.pc);let nextPc=loadPcContext(next);let selection;
  if(state.tab==='party'){const index=appendPartyPokemon(next,{speciesId,level});saveAll(next,nextPc);selection={kind:'party',index};}
  else{const occupied=new Set(getPcBox(nextPc,state.box,state.species,state.speciesMeta).map(m=>Number(m.slot)));const writable=getWritablePcSlots(nextPc,state.box);const slot=writable.find(s=>!occupied.has(Number(s)));if(!slot)throw new Error('No writable empty slot is available in this box.');const result=insertPcMon(nextPc,{box:state.box,slot,species_id:speciesId,level,exp:expAtLevelForSpecies(speciesId,level),moves:[0,0,0,0],ivs:{HP:31,Atk:31,Def:31,Spe:31,SpA:31,SpD:31},evs:{HP:0,Atk:0,Def:0,Spe:0,SpA:0,SpD:0},nature_id:0,item_id:0,current_ability_index:0,shiny:false},state.species);saveAll(next,nextPc);selection={kind:'pc',box:result.box,slot:result.slot};}
  nextPc=loadPcContext(next);const rb=selection.kind==='party'?getParty(next,state.species,state.speciesMeta).find(m=>m.index===selection.index):getPcBox(nextPc,selection.box,state.species,state.speciesMeta).find(m=>m.slot===selection.slot);if(!rb||Number(rb.species_id)!==speciesId)throw new Error('Created Pokémon failed readback validation; changes were not kept.');state.bytes=next;state.pc=nextPc;state.selected=selection;state.editCount++;state.formDirty=false;$('edit-count').textContent=`${state.editCount} saved ${state.editCount===1?'edit':'edits'}`;$('creator').hidden=true;renderList();renderEditor();message(`Created ${speciesName(speciesId)} at ${selection.kind==='party'?`Party slot ${selection.index+1}`:`Box ${selection.box}, slot ${selection.slot}`}. You can edit it now.`);
}catch(error){message(error.message||String(error),true)}}

async function fileHash(bytes){try{const h=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}catch{return null}}
async function openFile(file){if(!file)return;try{message('Reading save…');const bytes=new Uint8Array(await file.arrayBuffer());if(bytes.length!==0x20000&&bytes.length!==0x20010)throw new Error('Expected a 128 KiB Unbound .sav/.srm file (with an optional 16-byte trailer).');if(!findActiveSectionById(bytes,1))throw new Error('Trainer save section not found. Check that this is an in-game Unbound save, not a save state.');const pc=loadPcContext(bytes);getParty(bytes,state.species,state.speciesMeta);state.original=new Uint8Array(bytes);state.bytes=new Uint8Array(bytes);state.pc=pc;state.fileName=file.name||'unbound.sav';state.tab='party';state.box=1;state.selected=null;state.editCount=0;state.formDirty=false;$('workspace').hidden=false;$('export-panel').hidden=false;$('edit-count').textContent='No edits yet';$('box-select').value='1';$('creator').hidden=true;renderList();renderEditor();const hash=await fileHash(bytes);$('file-caption').textContent=`${state.fileName} · ${bytes.length.toLocaleString()} bytes${hash?` · SHA-256 ${hash.slice(0,12)}…`:''}`;message('Save loaded. Edit an existing Pokémon or use Add Pokémon.');}catch(error){message(error.message||String(error),true)}}
function download(ext){if(!state.bytes)return;try{const corrected=saveAll(new Uint8Array(state.bytes),state.pc);const sourceExt=state.fileName.toLowerCase().match(/\.(sav|srm)$/)?.[0];const output=sourceExt===ext?corrected:convertSaveBytes(corrected,ext);const base=state.fileName.replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9._ -]/g,'_').slice(0,70)||'unbound';const name=`${base}-v040-unified-edited${ext}`;const url=URL.createObjectURL(new Blob([output],{type:'application/octet-stream'}));const link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);message(`${name} is ready. Preserve your original save before replacing the emulator copy.`)}catch(error){message(error.message||String(error),true)}}

async function init(){try{await loadCatalog();[state.items,state.moves,state.species,state.speciesMeta]=await Promise.all([getItemsList(),getMovesList(),getSpeciesMap(),getSpeciesFormMetaMap()]);buildSpeciesList();const box=$('box-select');for(let i=1;i<=25;i++)box.append(option(i,`Box ${i}`));box.append(option(26,'Preset'));$('save-file').addEventListener('change',e=>openFile(e.target.files?.[0]));const drop=document.querySelector('.dropzone');for(const n of ['dragenter','dragover'])drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add('dragover')});for(const n of ['dragleave','drop'])drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove('dragover')});drop.addEventListener('drop',e=>openFile(e.dataTransfer?.files?.[0]));$('party-tab').addEventListener('click',()=>setTab('party'));$('pc-tab').addEventListener('click',()=>setTab('pc'));box.addEventListener('change',()=>{if(!confirmDiscard()){box.value=String(state.box);return}state.box=Number(box.value);state.selected=null;state.formDirty=false;$('creator').hidden=true;renderList();renderEditor()});$('add-mon').addEventListener('click',openCreator);$('close-creator').addEventListener('click',closeCreator);$('cancel-create').addEventListener('click',closeCreator);$('creator').addEventListener('submit',createPokemon);$('close-editor').addEventListener('click',()=>{if(!confirmDiscard())return;state.selected=null;state.formDirty=false;renderList();renderEditor()});for(const id of ['create-species','species','item','move-0','move-1','move-2','move-3']){$(`search-${id}`).addEventListener('input',e=>{e.stopPropagation();filterSelect(id)})}$('editor').addEventListener('change',()=>{state.formDirty=true});$('editor').addEventListener('input',()=>{state.formDirty=true});$('species').addEventListener('change',()=>{const id=Number($('species').value);populateGender(id,$('gender').value);populateAbility(id,0);state.formDirty=true});$('editor').addEventListener('submit',applyChanges);$('export-sav').addEventListener('click',()=>download('.sav'));$('export-srm').addEventListener('click',()=>download('.srm'));message('v0.5.0 CP33 editor ready. Select an Unbound v2.1.1.1 save to begin.');}catch(error){message(`Editor could not start: ${error.message||error}`,true)}}
init();
